### ISSUE TITLE
Dynamische data

### ISSUE THREAD

**Issue by KoopReynders** [tomsnep/browser-technologies#10]
Wat doe je als er data dynamisch binnenkomt. Dit moet je laten zien.

**Comment by tomsnep** [comment]
Ik heb de demo omgegooid op aanraden van krijn en gebruik nu aparte html files waar de score's in staan. De data wordt opgehaald vanuit deze files. Dit is dynamisch, als er een html file aan wordt toegevoegd zal deze score ook worden getoond.
